// English UI strings, the reference table: th.ts must have exactly the same keys.
// Placeholders look like {name}. A key with a ".one" twin uses it when count is 1.
// Brand names (Tamra, ตำรา) and model names are not translated.
export const en = {
  "common.cancel": "Cancel",
  "common.close": "Close",
  "common.dismiss": "Dismiss",
  "common.retry": "Retry",

  "app.newChat": "New chat",
  "app.chats": "Chats",
  "app.noChatsNoFolder": "No chats yet. Add a folder of documents to start.",
  "app.noChatsYet": "No chats yet. Ask a question to start one.",
  "app.coreUnreachable": "Tamra core is unreachable. Answers are paused until it reconnects.",
  "app.connecting": "Connecting to Tamra…",

  "folder.changeTitle": "Change documents folder",
  "folder.chooseTitle": "Choose documents folder",
  "folder.changeText":
    "Tamra will index the new folder and answer from it. Your files are never changed.",
  "folder.chooseText":
    "Tamra indexes the PDF, Word, text, and Markdown files in this folder and its subfolders. Your files are never changed.",
  "folder.pathLabel": "Folder path",
  "folder.pathPlaceholder": "Full folder path, like D:\\Work\\Documents",
  "folder.browse": "Browse…",
  "folder.use": "Use this folder",

  "welcome.title": "Welcome to Tamra",
  "welcome.subtitle":
    "Ask questions about your own documents and check every answer against its source.",
  "welcome.addTitle": "Add a folder of documents",
  "welcome.addText": "Choose a folder of PDF, Word, text, or Markdown files.",
  "welcome.choose": "Choose a folder",
  "welcome.offline": "Works offline",
  "welcome.cites": "Answers cite their source",
  "welcome.languages": "Thai, English, and Chinese",

  "deleteChat.title": "Delete this chat?",
  "deleteChat.text":
    "\"{title}\" will be removed from this computer. Your documents are not changed.",
  "deleteChat.confirm": "Delete chat",

  "chatList.untitled": "New chat",
  "chatList.options": "Options for {title}",
  "chatList.menu": "Chat options",
  "chatList.rename": "Rename",
  "chatList.delete": "Delete chat",
  "chatList.renameLabel": "Chat title",
  "chatList.renameHint": "Enter to save · Esc to cancel",

  "chat.defaultCollection": "your documents",
  "chat.emptyTitle": "Ask your documents",
  "chat.emptyText": "Every answer cites the passage it came from, so you can check it.",
  "chat.searching": "Searching your documents…",
  "chat.questionLabel": "Question",
  "chat.placeholder": "Ask about your documents…",
  "chat.send": "Send",
  "chat.stop": "Stop",
  "chat.composerHint": "Enter to send · Shift+Enter for a new line",
  "chat.notFoundTitle": "Not found in {name}",
  "chat.notFoundText": "Tamra answers only from your documents, so it will not guess.",
  "chat.citeHint": "Click a number to see the passage it came from.",
  "chat.cite": "Source {n}",
  "chat.sourcePanel": "Source",
  "chat.closeSource": "Close source",
  "chat.streamEmpty": "The answer stream is empty.",
  "chat.mode.menu": "How Tamra responds",
  "chat.mode.answer": "Answer",
  "chat.mode.answerText": "Writes an answer and cites every passage it used.",
  "chat.mode.search": "Search only",
  "chat.mode.searchText": "Shows the matching passages. No AI-written text.",
  "chat.think": "Think longer",
  "chat.thinkUnavailable": "This model cannot think longer.",
  "chat.thinking": "Thinking…",
  "chat.thought": "Thought for {seconds} s",
  "chat.thoughtMeta": "thought for {seconds} s",
  "chat.seconds": "{seconds} s",
  "chat.passages": "Passages found",
  "chat.providerLocal": "local",
  "chat.error.offline": "Could not reach the model. Check your internet connection and try again.",
  "chat.error.auth": "The API key is missing or was refused. Check it in Settings.",
  "chat.error.quota": "The provider's usage limit was reached. Try again later.",
  "chat.error.modelMissing":
    "No model is ready to answer. Choose or download one in Settings.",
  "chat.openModelSettings": "Open model settings",

  "model.chip": "Model",
  "model.menu": "Choose a model",
  "model.onThisComputer": "On this computer",
  "model.cloud": "Cloud API",
  "model.manage": "Manage models…",
  "model.none": "No model",
  "model.noneInstalled": "No model installed yet.",
  "model.tier.small": "Small",
  "model.tier.medium": "Medium",
  "model.tier.large": "Large",
  "model.canThink": "can think longer",
  "model.downloading": "downloading {percent}%",
  "model.verifying": "verifying…",
  "model.imported": "Imported model",
  "model.cloudSent": "{provider} · passages are sent to the provider",
  "model.cloudNoKey": "{provider} · add an API key in Settings first",

  "index.cardLabel": "Documents folder",
  "index.changeFolder": "Change folder",
  "index.rebuild": "Rebuild index",
  "index.stale":
    "This index was built with a different embedding model. Rebuild it to search again.",
  "index.checking": "Checking files…",
  "index.none": "No documents found yet",
  "index.progress": "Indexing progress",
  "index.partial": "{indexed} of {total} files indexed",
  "index.filesIndexed": "{count} files indexed",
  "index.filesIndexed.one": "1 file indexed",
  "index.current": "Indexing {file}",
  "index.needAttention": "{count} files need attention",
  "index.needAttention.one": "1 file needs attention",
  "index.failed": "Failed: {error}",
  "index.skipped": "Skipped: {error}",
  "index.failedBare": "Failed",
  "index.skippedBare": "Skipped",

  "settings.open": "Settings",
  "settings.title": "Settings",
  "settings.subtitle.general": "Language, documents, and the data Tamra keeps on this computer.",
  "settings.subtitle.model":
    "Choose where answers are generated. Search and indexing always run on this computer.",
  "settings.subtitle.style":
    "How Tamra looks. These choices change the app only, never your documents.",
  "settings.tabs": "Settings sections",
  "settings.tab.general": "General",
  "settings.tab.model": "AI model",
  "settings.tab.style": "Style",

  "settings.general": "General",
  "settings.language": "Interface language",
  "settings.languageHint": "Answers always follow the language of your question.",
  "settings.askBeforeDelete": "Ask before deleting a chat",
  "settings.documents": "Documents",
  "settings.docFolder": "Documents folder",
  "settings.noFolder": "No folder chosen yet",
  "settings.changeFolder": "Change folder",
  "settings.chooseFolder": "Choose a folder",
  "settings.searchIndex": "Search index",
  "settings.indexSummary": "{count} files indexed · built with bge-m3",
  "settings.indexSummary.one": "1 file indexed · built with bge-m3",
  "settings.indexPartial": "{indexed} of {total} files indexed · built with bge-m3",
  "settings.indexNone": "No files indexed yet · built with bge-m3",
  "settings.rebuild": "Rebuild index",
  "settings.data": "Data",
  "settings.dataFolder": "Data folder",
  "settings.openFolder": "Open folder",
  "settings.openFolderUnavailable": "Only available in the Tamra window.",
  "settings.chatHistory": "Chat history",
  "settings.chatCount": "{count} chats saved on this computer",
  "settings.chatCount.one": "1 chat saved on this computer",
  "settings.chatCountNone": "No chats saved yet",
  "settings.deleteAll": "Delete all chats",
  "settings.deleteAllTitle": "Delete all chats?",
  "settings.deleteAllText":
    "All {count} chats will be removed from this computer. Your documents are not changed.",
  "settings.deleteAllText.one":
    "The chat will be removed from this computer. Your documents are not changed.",
  "settings.footer": "Tamra · pre-alpha · Apache-2.0 license",

  "settings.aiMode": "AI mode",
  "settings.modeLocal": "Local model",
  "settings.modeLocalText": "Runs on this computer. Nothing leaves it.",
  "settings.modeCloud": "Cloud API",
  "settings.modeCloudText": "Anthropic or any OpenAI-compatible server. Usually better answers.",
  "settings.localModel": "Local model",
  "settings.detected": "Detected {ram} GB RAM · {gpu}",
  "settings.gpu": "{name}, {vram} GB VRAM",
  "settings.noGpu": "no dedicated GPU",
  "settings.recommended": "Recommended",
  "settings.installed": "Installed",
  "settings.downloadingPercent": "Downloading {percent}%",
  "settings.verifying": "Verifying…",
  "settings.download": "Download",
  "settings.cancelDownload": "Cancel download",
  "settings.downloadFailed": "Download failed: {error}",
  "settings.forCpu": "for CPU-only machines",
  "settings.needsGpu": "needs a GPU with {gb} GB VRAM or more",
  "settings.downloadTitle": "Download {name} ({size})?",
  "settings.downloadText":
    "Tamra downloads the file once and checks it before use. This needs an internet connection and free disk space.",
  "settings.alreadyInstalled": "This model is already installed.",
  "settings.sizeGb": "{size} GB",
  "settings.sizeMb": "{size} MB",
  "settings.uncatalogued": "Not in Tamra's catalog; answer quality is unknown.",
  "settings.importButton": "Import model file…",
  "settings.importHint":
    "For computers without internet. The file is checked against the model catalog.",
  "settings.importPathLabel": "Model file path",
  "settings.importPathPlaceholder": "Full path to a .gguf file, like D:\\Models\\model.gguf",
  "settings.importGo": "Import",
  "settings.importing": "Importing…",
  "settings.importedCatalogued": "Imported {file}. It matches the model catalog.",
  "settings.importedOther": "Imported {file}. {warning}",

  "settings.cloudWarning":
    "In API mode, the passages found for each question are sent to the provider. Your files and the search index stay on this computer.",
  "settings.provider": "Provider",
  "settings.providerAnthropic": "Anthropic",
  "settings.providerOpenai": "OpenAI-compatible",
  "settings.apiModel": "Model",
  "settings.baseUrl": "Base URL",
  "settings.baseUrlPlaceholder": "Only for OpenAI-compatible servers",
  "settings.apiKey": "API key",
  "settings.apiKeyPlaceholder": "Paste your API key",
  "settings.apiKeyNote": "Stored in Windows Credential Manager, never in Tamra's files.",
  "settings.save": "Save",
  "settings.saved": "Saved",
  "settings.test": "Test connection",
  "settings.testing": "Testing…",
  "settings.testHint": "Test connection saves your changes, then tests them.",
  "settings.connected": "Connected",
  "settings.test.offline":
    "Could not reach the provider. Check your internet connection and the Base URL.",
  "settings.test.auth": "The API key is missing or was refused.",
  "settings.test.quota": "The provider's usage limit was reached. Try again later.",
  "settings.test.modelMissing": "The provider does not know this model. Check the model name.",

  "settings.theme": "Theme",
  "settings.theme.light": "Light",
  "settings.theme.dark": "Dark",
  "settings.theme.system": "Match Windows",
  "settings.colourText": "Colour and text",
  "settings.accent": "Accent colour",
  "settings.accentHint": "Used for buttons, links, and citation markers.",
  "settings.accent.green": "Green",
  "settings.accent.blue": "Blue",
  "settings.accent.orange": "Orange",
  "settings.accent.purple": "Purple",
  "settings.accent.slate": "Slate",
  "settings.textSize": "Text size",
  "settings.textSizeHint": "Applies to questions, answers, and source passages.",
  "settings.size.small": "Small",
  "settings.size.default": "Default",
  "settings.size.large": "Large",
  "settings.spacing": "Spacing",
  "settings.spacing.comfortable": "Comfortable",
  "settings.spacing.compact": "Compact",
  "settings.preview": "Preview",
  "settings.previewQuestion": "How many days of leave does a new employee get?",
  "settings.previewAnswer": "A new employee gets 6 days of leave a year, after the probation period.",
} as const;

export type TranslationKey = keyof typeof en;
