// Thai UI strings. Same keys as en.ts (checked by the compiler and by i18n.test.ts).
// Thai has no plural forms, so a ".one" key repeats the base wording.
import type { TranslationKey } from "./en";

export const th: Record<TranslationKey, string> = {
  "common.cancel": "ยกเลิก",
  "common.close": "ปิด",
  "common.dismiss": "ปิด",
  "common.retry": "ลองอีกครั้ง",

  "app.newChat": "แชทใหม่",
  "app.chats": "แชท",
  "app.noChatsNoFolder": "ยังไม่มีแชท เพิ่มโฟลเดอร์เอกสารเพื่อเริ่มต้นใช้งาน",
  "app.noChatsYet": "ยังไม่มีแชท ลองถามคำถามเพื่อเริ่มแชทแรก",
  "app.coreUnreachable":
    "เชื่อมต่อระบบหลักของ Tamra ไม่ได้ การตอบคำถามจะหยุดไว้ก่อนจนกว่าจะเชื่อมต่อได้อีกครั้ง",
  "app.connecting": "กำลังเชื่อมต่อ Tamra…",

  "folder.changeTitle": "เปลี่ยนโฟลเดอร์เอกสาร",
  "folder.chooseTitle": "เลือกโฟลเดอร์เอกสาร",
  "folder.changeText":
    "Tamra จะสร้างดัชนีของโฟลเดอร์ใหม่และตอบจากโฟลเดอร์นี้ ไฟล์ของคุณจะไม่ถูกแก้ไข",
  "folder.chooseText":
    "Tamra จะสร้างดัชนีของไฟล์ PDF, Word, ข้อความ และ Markdown ในโฟลเดอร์นี้และโฟลเดอร์ย่อยทั้งหมด ไฟล์ของคุณจะไม่ถูกแก้ไข",
  "folder.pathLabel": "ที่อยู่โฟลเดอร์",
  "folder.pathPlaceholder": "ใส่ที่อยู่โฟลเดอร์แบบเต็ม เช่น D:\\Work\\Documents",
  "folder.browse": "เรียกดู…",
  "folder.use": "ใช้โฟลเดอร์นี้",

  "welcome.title": "ยินดีต้อนรับสู่ Tamra",
  "welcome.subtitle": "ถามคำถามจากเอกสารของคุณเอง แล้วตรวจคำตอบกับต้นฉบับได้ทุกข้อ",
  "welcome.addTitle": "เพิ่มโฟลเดอร์เอกสาร",
  "welcome.addText": "เลือกโฟลเดอร์ที่มีไฟล์ PDF, Word, ข้อความ หรือ Markdown",
  "welcome.choose": "เลือกโฟลเดอร์",
  "welcome.offline": "ใช้งานได้โดยไม่ต้องออนไลน์",
  "welcome.cites": "คำตอบอ้างอิงแหล่งที่มา",
  "welcome.languages": "รองรับไทย อังกฤษ และจีน",

  "deleteChat.title": "ลบแชทนี้หรือไม่",
  "deleteChat.text": "“{title}” จะถูกลบออกจากคอมพิวเตอร์เครื่องนี้ เอกสารของคุณจะไม่ถูกแก้ไข",
  "deleteChat.confirm": "ลบแชท",

  "chatList.untitled": "แชทใหม่",
  "chatList.options": "ตัวเลือกของ {title}",
  "chatList.menu": "ตัวเลือกแชท",
  "chatList.rename": "เปลี่ยนชื่อ",
  "chatList.delete": "ลบแชท",
  "chatList.renameLabel": "ชื่อแชท",
  "chatList.renameHint": "กด Enter เพื่อบันทึก · กด Esc เพื่อยกเลิก",

  "chat.defaultCollection": "เอกสารของคุณ",
  "chat.emptyTitle": "ถามจากเอกสารของคุณ",
  "chat.emptyText": "ทุกคำตอบจะอ้างอิงข้อความต้นฉบับที่ใช้ตอบ คุณจึงตรวจสอบได้เอง",
  "chat.searching": "กำลังค้นหาในเอกสารของคุณ…",
  "chat.questionLabel": "คำถาม",
  "chat.placeholder": "ถามเกี่ยวกับเอกสารของคุณ…",
  "chat.send": "ส่ง",
  "chat.stop": "หยุด",
  "chat.composerHint": "กด Enter เพื่อส่ง · กด Shift+Enter เพื่อขึ้นบรรทัดใหม่",
  "chat.notFoundTitle": "ไม่พบใน {name}",
  "chat.notFoundText": "Tamra ตอบจากเอกสารของคุณเท่านั้น จึงไม่เดาคำตอบเอง",
  "chat.citeHint": "คลิกตัวเลขเพื่อดูข้อความต้นฉบับที่ใช้ตอบ",
  "chat.cite": "แหล่งที่มา {n}",
  "chat.sourcePanel": "แหล่งที่มา",
  "chat.closeSource": "ปิดแหล่งที่มา",
  "chat.checkSource": "ตรวจสอบแหล่งที่มา",
  "source.open": "เปิดไฟล์",
  "source.compare": "เปรียบเทียบ",
  "source.answer": "คำตอบ",
  "source.document": "เอกสาร",
  "source.strong": "ตรงมาก",
  "source.partial": "ตรงบางส่วน",
  "source.matchOf": "{index} จาก {count}",
  "source.previous": "ผลที่ตรงก่อนหน้า",
  "source.next": "ผลที่ตรงถัดไป",
  "source.changed":
    "เอกสารนี้เปลี่ยนไปหลังจากตอบแล้ว กำลังแสดงข้อความที่ Tamra ใช้ในตอนนั้น",
  "source.none": "ไม่พบแหล่งที่มาที่ชัดเจนสำหรับข้อความที่เลือก",
  "source.noneList": "เปิดดูแหล่งที่มาของคำตอบนี้เองได้",
  "source.checking": "กำลังตรวจสอบแหล่งที่มา…",
  "source.failed": "ตรวจสอบข้อความที่เลือกไม่สำเร็จ",
  "source.pageOf": "หน้า {page} จาก {count}",
  "source.line": "บรรทัด {n}",
  "source.lines": "บรรทัด {from}–{to}",
  "chat.streamEmpty": "ไม่ได้รับข้อมูลคำตอบ",
  "chat.mode.menu": "วิธีที่ Tamra ตอบ",
  "chat.mode.answer": "ตอบคำถาม",
  "chat.mode.answerText": "เขียนคำตอบและอ้างอิงทุกข้อความที่ใช้",
  "chat.mode.search": "ค้นหาอย่างเดียว",
  "chat.mode.searchText": "แสดงข้อความที่ตรงกับคำถาม ไม่มีข้อความที่ AI เขียน",
  "chat.think": "คิดให้ลึกขึ้น",
  "chat.thinkUnavailable": "โมเดลนี้คิดให้ลึกขึ้นไม่ได้",
  "chat.thinking": "กำลังคิด…",
  "chat.thought": "คิดไป {seconds} วินาที",
  "chat.thoughtMeta": "คิดไป {seconds} วินาที",
  "chat.seconds": "{seconds} วิ",
  "chat.passages": "ข้อความที่พบ",
  "chat.providerLocal": "ในเครื่อง",
  "chat.error.offline": "เชื่อมต่อโมเดลไม่ได้ ตรวจสอบอินเทอร์เน็ตแล้วลองอีกครั้ง",
  "chat.error.auth": "ยังไม่ได้ตั้งค่าคีย์ API หรือผู้ให้บริการไม่รับคีย์นี้ ตรวจสอบได้ในการตั้งค่า",
  "chat.error.quota": "ถึงขีดจำกัดการใช้งานของผู้ให้บริการแล้ว ลองอีกครั้งภายหลัง",
  "chat.error.modelMissing": "ยังไม่มีโมเดลที่พร้อมตอบ เลือกหรือดาวน์โหลดโมเดลในการตั้งค่า",
  "chat.openModelSettings": "เปิดการตั้งค่าโมเดล",
  "chat.useLocal": "ใช้โมเดลในเครื่อง",

  "model.chip": "โมเดล",
  "model.menu": "เลือกโมเดล",
  "model.onThisComputer": "ในเครื่องนี้",
  "model.cloud": "API บนคลาวด์",
  "model.manage": "จัดการโมเดล…",
  "model.none": "ไม่มีโมเดล",
  "model.noneInstalled": "ยังไม่ได้ติดตั้งโมเดล",
  "model.tier.small": "ขนาดเล็ก",
  "model.tier.medium": "ขนาดกลาง",
  "model.tier.large": "ขนาดใหญ่",
  "model.canThink": "คิดให้ลึกขึ้นได้",
  "model.downloading": "กำลังดาวน์โหลด {percent}%",
  "model.verifying": "กำลังตรวจสอบไฟล์…",
  "model.imported": "โมเดลที่นำเข้า",
  "model.cloudSent": "{provider} · ข้อความที่ค้นพบจะถูกส่งให้ผู้ให้บริการ",
  "model.cloudNoKey": "{provider} · ตั้งค่าคีย์ API ในการตั้งค่าก่อน",
  "model.cpuFallback":
    "โมเดลกำลังทำงานบน CPU เพราะใช้ GPU ไม่ได้ คำตอบจึงจะช้ากว่าปกติ",

  "index.cardLabel": "โฟลเดอร์เอกสาร",
  "index.changeFolder": "เปลี่ยนโฟลเดอร์",
  "index.rebuild": "สร้างดัชนีใหม่",
  "index.stale":
    "ดัชนีนี้สร้างด้วยโมเดล embedding ตัวอื่น ต้องสร้างใหม่จึงจะค้นหาได้อีกครั้ง",
  "index.checking": "กำลังตรวจสอบไฟล์…",
  "index.none": "ยังไม่พบเอกสาร",
  "index.progress": "ความคืบหน้าการสร้างดัชนี",
  "index.partial": "สร้างดัชนีแล้ว {indexed} จาก {total} ไฟล์",
  "index.filesIndexed": "สร้างดัชนีแล้ว {count} ไฟล์",
  "index.filesIndexed.one": "สร้างดัชนีแล้ว 1 ไฟล์",
  "index.current": "กำลังสร้างดัชนี {file}",
  "index.needAttention": "{count} ไฟล์ต้องตรวจสอบ",
  "index.needAttention.one": "1 ไฟล์ต้องตรวจสอบ",
  "index.failed": "ล้มเหลว: {error}",
  "index.skipped": "ข้ามไฟล์: {error}",
  "index.failedBare": "ล้มเหลว",
  "index.skippedBare": "ข้ามไฟล์",

  "settings.open": "การตั้งค่า",
  "settings.title": "การตั้งค่า",
  "settings.subtitle.general": "ภาษา เอกสาร และข้อมูลที่ Tamra เก็บไว้ในคอมพิวเตอร์เครื่องนี้",
  "settings.subtitle.model":
    "เลือกว่าจะให้สร้างคำตอบที่ไหน การค้นหาและการสร้างดัชนีทำงานในคอมพิวเตอร์เครื่องนี้เสมอ",
  "settings.subtitle.style":
    "หน้าตาของ Tamra ตัวเลือกเหล่านี้เปลี่ยนเฉพาะตัวแอป ไม่แตะต้องเอกสารของคุณ",
  "settings.tabs": "หมวดการตั้งค่า",
  "settings.tab.general": "ทั่วไป",
  "settings.tab.model": "โมเดล AI",
  "settings.tab.style": "รูปลักษณ์",

  "settings.general": "ทั่วไป",
  "settings.language": "ภาษาของแอป",
  "settings.languageHint": "คำตอบจะใช้ภาษาเดียวกับคำถามของคุณเสมอ",
  "settings.askBeforeDelete": "ถามก่อนลบแชท",
  "settings.documents": "เอกสาร",
  "settings.docFolder": "โฟลเดอร์เอกสาร",
  "settings.noFolder": "ยังไม่ได้เลือกโฟลเดอร์",
  "settings.changeFolder": "เปลี่ยนโฟลเดอร์",
  "settings.chooseFolder": "เลือกโฟลเดอร์",
  "settings.searchIndex": "ดัชนีการค้นหา",
  "settings.indexSummary": "สร้างดัชนีแล้ว {count} ไฟล์ · สร้างด้วย bge-m3",
  "settings.indexSummary.one": "สร้างดัชนีแล้ว 1 ไฟล์ · สร้างด้วย bge-m3",
  "settings.indexPartial": "สร้างดัชนีแล้ว {indexed} จาก {total} ไฟล์ · สร้างด้วย bge-m3",
  "settings.indexNone": "ยังไม่มีไฟล์ที่สร้างดัชนี · สร้างด้วย bge-m3",
  "settings.rebuild": "สร้างดัชนีใหม่",
  "settings.data": "ข้อมูล",
  "settings.dataFolder": "โฟลเดอร์ข้อมูล",
  "settings.openFolder": "เปิดโฟลเดอร์",
  "settings.openFolderUnavailable": "ใช้ได้เฉพาะในหน้าต่าง Tamra",
  "settings.chatHistory": "ประวัติแชท",
  "settings.chatCount": "บันทึกแชทไว้ในเครื่องนี้ {count} แชท",
  "settings.chatCount.one": "บันทึกแชทไว้ในเครื่องนี้ 1 แชท",
  "settings.chatCountNone": "ยังไม่มีแชทที่บันทึกไว้",
  "settings.deleteAll": "ลบแชททั้งหมด",
  "settings.deleteAllTitle": "ลบแชททั้งหมดหรือไม่",
  "settings.deleteAllText":
    "แชททั้ง {count} แชทจะถูกลบออกจากคอมพิวเตอร์เครื่องนี้ เอกสารของคุณจะไม่ถูกแก้ไข",
  "settings.deleteAllText.one":
    "แชทนี้จะถูกลบออกจากคอมพิวเตอร์เครื่องนี้ เอกสารของคุณจะไม่ถูกแก้ไข",
  "settings.footer": "Tamra · pre-alpha · สัญญาอนุญาต Apache-2.0",

  "settings.aiMode": "โหมด AI",
  "settings.modeLocal": "โมเดลในเครื่อง",
  "settings.modeLocalText": "ทำงานในคอมพิวเตอร์เครื่องนี้ ไม่มีอะไรออกไปนอกเครื่อง",
  "settings.modeCloud": "API บนคลาวด์",
  "settings.modeCloudText":
    "Anthropic หรือเซิร์ฟเวอร์ที่เข้ากันได้กับ OpenAI มักให้คำตอบที่ดีกว่า",
  "settings.localModel": "โมเดลในเครื่อง",
  "settings.detected": "ตรวจพบ RAM {ram} GB · {gpu}",
  "settings.gpu": "{name} VRAM {vram} GB",
  "settings.noGpu": "ไม่มี GPU แยก",
  "settings.recommended": "แนะนำ",
  "settings.installed": "ติดตั้งแล้ว",
  "settings.downloadingPercent": "กำลังดาวน์โหลด {percent}%",
  "settings.verifying": "กำลังตรวจสอบไฟล์…",
  "settings.download": "ดาวน์โหลด",
  "settings.cancelDownload": "ยกเลิกการดาวน์โหลด",
  "settings.downloadFailed": "ดาวน์โหลดไม่สำเร็จ: {error}",
  "settings.forCpu": "เหมาะกับเครื่องที่ใช้ CPU อย่างเดียว",
  "settings.needsGpu": "ต้องใช้ GPU ที่มี VRAM {gb} GB ขึ้นไป",
  "settings.downloadTitle": "ดาวน์โหลด {name} ({size}) หรือไม่",
  "settings.downloadText":
    "Tamra จะดาวน์โหลดไฟล์ครั้งเดียวและตรวจสอบก่อนใช้งาน ต้องเชื่อมต่ออินเทอร์เน็ตและมีพื้นที่ดิสก์ว่างเพียงพอ",
  "settings.alreadyInstalled": "ติดตั้งโมเดลนี้แล้ว",
  "settings.downloadBusy": "กำลังดาวน์โหลดโมเดลอื่นอยู่ รอให้เสร็จก่อนแล้วลองอีกครั้ง",
  "settings.sizeGb": "{size} GB",
  "settings.sizeMb": "{size} MB",
  "settings.uncatalogued": "ไม่อยู่ในแคตตาล็อกของ Tamra จึงไม่ทราบคุณภาพของคำตอบ",
  "settings.importButton": "นำเข้าไฟล์โมเดล…",
  "settings.importHint": "สำหรับเครื่องที่ไม่มีอินเทอร์เน็ต ไฟล์จะถูกตรวจสอบกับแคตตาล็อกโมเดล",
  "settings.importPathLabel": "ที่อยู่ไฟล์โมเดล",
  "settings.importPathPlaceholder": "ใส่ที่อยู่ไฟล์ .gguf แบบเต็ม เช่น D:\\Models\\model.gguf",
  "settings.importGo": "นำเข้า",
  "settings.importing": "กำลังนำเข้า…",
  "settings.importedCatalogued": "นำเข้า {file} แล้ว ตรงกับแคตตาล็อกโมเดล",
  "settings.importedOther": "นำเข้า {file} แล้ว {warning}",

  "settings.cloudWarning":
    "ในโหมด API ข้อความที่ค้นพบสำหรับแต่ละคำถามจะถูกส่งให้ผู้ให้บริการ ไฟล์ของคุณและดัชนีการค้นหายังอยู่ในคอมพิวเตอร์เครื่องนี้",
  "settings.provider": "ผู้ให้บริการ",
  "settings.providerAnthropic": "Anthropic",
  "settings.providerOpenai": "เข้ากันได้กับ OpenAI",
  "settings.apiModel": "โมเดล",
  "settings.baseUrl": "Base URL",
  "settings.baseUrlPlaceholder": "ใช้กับเซิร์ฟเวอร์ที่เข้ากันได้กับ OpenAI เท่านั้น",
  "settings.apiKey": "คีย์ API",
  "settings.apiKeyPlaceholder": "วางคีย์ API ที่นี่",
  "settings.apiKeyNote": "เก็บไว้ใน Windows Credential Manager ไม่เก็บในไฟล์ของ Tamra",
  "settings.removeKey": "ลบคีย์",
  "settings.removeKeyTitle": "ลบคีย์ API ของ {provider} หรือไม่",
  "settings.removeKeyText":
    "คีย์จะถูกลบออกจาก Windows Credential Manager หากต้องการใช้ผู้ให้บริการนี้อีก ต้องวางคีย์ใหม่",
  "settings.keyRemoved": "ลบคีย์แล้ว",
  "settings.modelRequired": "ต้องระบุชื่อโมเดล",
  "settings.baseUrlInvalid":
    "Base URL ต้องขึ้นต้นด้วย http:// หรือ https:// และห้ามมีชื่อผู้ใช้ พารามิเตอร์ หรือ #",
  "settings.save": "บันทึก",
  "settings.saved": "บันทึกแล้ว",
  "settings.test": "ทดสอบการเชื่อมต่อ",
  "settings.testing": "กำลังทดสอบ…",
  "settings.testHint": "การทดสอบการเชื่อมต่อจะบันทึกการเปลี่ยนแปลงของคุณก่อน แล้วจึงทดสอบ",
  "settings.connected": "เชื่อมต่อได้",
  "settings.test.offline": "เชื่อมต่อผู้ให้บริการไม่ได้ ตรวจสอบอินเทอร์เน็ตและ Base URL",
  "settings.test.auth": "ยังไม่ได้ตั้งค่าคีย์ API หรือผู้ให้บริการไม่รับคีย์นี้",
  "settings.test.quota": "ถึงขีดจำกัดการใช้งานของผู้ให้บริการแล้ว ลองอีกครั้งภายหลัง",
  "settings.test.modelMissing": "ผู้ให้บริการไม่รู้จักโมเดลนี้ ตรวจสอบชื่อโมเดล",

  "settings.theme": "ธีม",
  "settings.theme.light": "สว่าง",
  "settings.theme.dark": "มืด",
  "settings.theme.system": "ตาม Windows",
  "settings.colourText": "สีและตัวอักษร",
  "settings.accent": "สีเน้น",
  "settings.accentHint": "ใช้กับปุ่ม ลิงก์ และเครื่องหมายอ้างอิง",
  "settings.accent.green": "เขียว",
  "settings.accent.blue": "น้ำเงิน",
  "settings.accent.orange": "ส้ม",
  "settings.accent.purple": "ม่วง",
  "settings.accent.slate": "เทาเข้ม",
  "settings.textSize": "ขนาดตัวอักษร",
  "settings.textSizeHint": "ใช้กับคำถาม คำตอบ และข้อความต้นฉบับ",
  "settings.size.small": "เล็ก",
  "settings.size.default": "ปกติ",
  "settings.size.large": "ใหญ่",
  "settings.spacing": "ระยะห่าง",
  "settings.spacing.comfortable": "สบายตา",
  "settings.spacing.compact": "กะทัดรัด",
  "settings.preview": "ตัวอย่าง",
  "settings.previewQuestion": "พนักงานใหม่ลาพักร้อนได้กี่วัน",
  "settings.previewAnswer": "พนักงานใหม่ลาพักร้อนได้ 6 วันต่อปี หลังผ่านช่วงทดลองงาน",
};
